export class RedsysPayment {
    DS_MERCHANT_TRANSACTIONTYPE:string;
    DS_MERCHANT_MERCHANTCODE:string;
    DS_MERCHANT_ORDER: string;
    DS_MERCHANT_EXPIRYDATE: string;
    // DS_MERCHANT_PAN: string;
    // DS_MERCHANT_CVV2: string;
    // DS_MERCHANT_COF_INI: string;
    DS_MERCHANT_TERMINAL:string;
    DS_MERCHANT_CURRENCY: string;
    DS_MERCHANT_IDENTIFIER: string;
    DS_MERCHANT_AMOUNT: string;
    // DS_MERCHANT_DIRECTPAYMENT:string;
    DS_MERCHANT_URLKO:string;
    DS_MERCHANT_URLOK:string;
    DS_MERCHANT_MERCHANTURL:string;
    DS_MERCHANT_MERCHANTDATA:string;
   }